# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8
      - image: postgres:10-alpine

    environment:
      POSTGRES_USER: cardless
      POSTGRES_PASSWORD: cardless

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: Rebuilding database
          command: npm run db:recreate

      - run:
          name: Seed database
          command: npm run db:seed

      - run:
          name: Lint code
          command: npm run lint:check

      - run:
          name: Run tests
          command: npm test

      - run: npm test
